### ISSUE TITLE
Support dark theme and custom themes

### ISSUE THREAD

**Issue by krlade** [karl0d/elegancia-hugo#1]
- [x] Add theme switcher (#6)
- [x] Make theme configurable in `config.toml` (#5)
- [x] Move to sass css (#5)
